### PR TITLE
LPS-69587 fix warn messenge log tests

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by diogo-lins** [comment]
Hi @ctampoya, when the CI finish running you will look that has four Poshi tests failed, this happens because the select field has now a new interaction and design, and the html markup <select> is now hidden in the DOM tree, so these tests wait for the select input visible in the page.

**Comment by ctampoya** [comment]
Hi @diogo-lins, Okay I will take a look at those tests =) Thanks!

**Comment by diogo-lins** [comment]
Thanks @ctampoya =)

**Comment by ctampoya** [comment]
Running all Forms tests https://github.com/ctampoya/liferay-portal/pull/50

**Comment by ctampoya** [comment]
Pushed to https://github.com/vicnate5/liferay-portal/pull/688

**Pull request closed without merging**
