### PR TITLE
LPS-71216 SF

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by vicnate5** [comment]
@thiago-rocha @rafaprax This allows the user to save an autofill rule, but I think the save button is activated too early. The Save button is activated as soon as the user chooses the Autofill action, even if no data provider has been chosen yet.

enablesavetooearly

CC @ctampoya

**Comment by rafaprax** [comment]
Hey @vicnate5 We didn't do the validation for the autofill and calculate actions yet. So, because of that the save button is enabled after chosen any of those actions. We'll implement those validations soon(they are already in our backlog). 

Thx

CC @ctampoya @thiago-rocha

**Comment by vicnate5** [comment]
@rafaprax Thanks for the explanation. I will temporarily remove the check for the Save button activity at this step in our poshi test. We can add the check back in once validation is fully implemented.

**Comment by rafaprax** [comment]
@vicnate5 No problem 👍

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/47644

**Pull request closed without merging**
