### PR TITLE
LPS-71827 SF

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
@ctampoya , now it should be good! :)

**Comment by pedroqueiroz** [comment]
hey @ctampoya , the test failed but this time it is not related to my pull request... what should I do?

**Comment by ctampoya** [comment]
@pedroqueiroz94 Since it was auto closed I will have to retest this one =)

**Comment by ctampoya** [comment]
ci:reopen

**Comment by ctampoya** [comment]
ci:retest

**Comment by ctampoya** [comment]
@pedroqueiroz94 Are those DDM/DDL integration tests related to the pull?

**Comment by ctampoya** [comment]
Pushed to https://github.com/leoadb/liferay-portal/pull/326

**Pull request closed without merging**
