### PR TITLE
LPS-69775 SF Unit Tests

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by thiago-rocha** [comment]
@pedroqueiroz94 @leoadb @diogo-lins

**Comment by ctampoya** [comment]
@thiago-rocha  Looks like a SF error with DDM module

**Comment by diogo-lins** [comment]
Hi @ctampoya, please don't reopen this one, I will fix the SF error and send to you soon.
Thx

**Comment by ctampoya** [comment]
Thank you @diogo-lins

**Pull request closed without merging**
