### PR TITLE
LPS-71986 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by ctampoya** [comment]
ci:reopen

**Comment by ctampoya** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by ctampoya** [comment]
@rafaprax Quarantined Forms test here https://github.com/vicnate5/liferay-portal/pull/808

**Comment by vicnate5** [comment]
ci:retest

**Comment by ctampoya** [comment]
Test re-enabled here https://github.com/vicnate5/liferay-portal/pull/809

**Pull request closed without merging**
