### PR TITLE
LPS-70446 Get data provider name in rule builder list

### PR DESCRIPTION
**Pull request by diogo-lins**
@ctampoya this PR fix this one (https://github.com/ctampoya/liferay-portal/pull/78)

### CODE REVIEW

**Comment by diogo-lins** [comment]
@ctampoya Could you wait to review this PR, I forgot to add a commit. Thx.

**Comment by diogo-lins** [comment]
Updated.

**Comment by diogo-lins** [comment]
ci:retest

**Comment by ctampoya** [comment]
Pushed to https://github.com/vicnate5/liferay-portal/pull/746

**Pull request closed without merging**
