### PR TITLE
LRQA-BUNDLES Trying out a fix for keeping bundles

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-34841

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
@ctampoya - I'm sending a pull to you to test out updates to save the bundle.

This is in regards to the failure to post the bundle in here:
https://github.com/liferay/liferay-portal-ee/pull/2691#issuecomment-334856205

**Comment by ctampoya** [comment]
@michaelhashimoto Looks like it worked

**Comment by ctampoya** [comment]
@michaelhashimoto Sorry.. I accidentally hit "Close and Comment" But it looks like the update worked

**Comment by michaelhashimoto** [comment]
@ctampoya - Thanks I'm pushing it up to bchan:
https://github.com/brianchandotcom/liferay-jenkins-ee/pull/2429

**Pull request closed without merging**
