### PR TITLE
LPS-68076 Value now is state false and fixes in logic repaintable attributes of field

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @vicnate5

### CODE REVIEW

**Comment by ctampoya** [comment]
Testing all Forms test https://github.com/ctampoya/liferay-portal/pull/25

**Comment by ctampoya** [comment]
@diogo-lins @fernandosouza I tested out the overall functionality of Form Rules and there are some issues I found in this pull. If you have questions about any of these please let me know.
cc @marcellustavares @brunobasto 

## Issue 1 - Required fields are not validated

Steps to Reproduce:
1. Add a Text field with label ‘Text’
2. Add a Date field with label ‘Date’
3. Go to Form Rules
4. Set Rule: **Condition IF**  ‘Text’ _is equal to_ ‘Value’ _”test”_  **Actions DO** _Require_ ‘Date’
5. Save Rule
6. Save Form
7. Add Form portlet to a page
8. Select created Form
9. Input text “test” in text field
10. Assert required icon appears on Date field
11. Leave Date field empty
12. Submit Form

_Result:_ Form submits successfully even though a blank required field has been
    submitted. 

## Issue 2 - Saving an empty Form Rule does not provide any type of error message

Steps to reproduce:
1. Go to Forms > Add a Form
2. Click on Rules tab
3. Click (+) to add a new rule
4. Do not make any edits > Save rule
5. Click on “Builder” tab

 _Result:_ 
- At step 4: There are no error messages that inform the User that they have not submitted a complete rule. [Refer to image](http://i.imgur.com/2Sis07r.png)
- At step 5: The Form appears as it would in the builder, however, the “Rules” tab is still the highlighted tab. Also, the “Save” button that is present on the Form builder is not present. The issue is fixed when the page is refreshed. [Refer to image](http://i.imgur.com/y38y7Nc.png)

## Issue 3 - If the constant value is a number, the rule does not work

 Steps to reproduce:
1. Add 2 text fields
2. Name one of the text fields “Number”
3. Name second field “Text”
4. Go to ‘Rules’ tab
5. Set Rule: **IF** ‘Number’ _is equal to_ ‘Value’ _”1234”_ **DO** _Show_ “Text”
6. Save Rule
7. Save Form
8. Add Form to a page and select created Form
9. Assert field _Number_ is present and field _Text_ is not present
10. Input value “1234” in Number field

_Result:_ Text field does not show up even though the rule has been met.

**Note** This also occurs when the values of the Radio or Checkbox field are numbers.
1. Instead of 2 Text fields, add a Radio and Text field
2. Configure Radio field to have field name “Radio” and Options “1” and “2” 
3. Configure Text field to have field name “Text”
4. Create Rule: **IF** ‘Radio’ _is equal to_ ‘Value’ _”1”_ **DO** _Show_ “Text”
5. Add Form to a page and select Radio option 1
_Result:_ Text field does not show up even though the rule has been met.

## Issue 4 - Errors when using conditions “is not equal to” and “does not contain”

Steps to Reproduce:
1. Add a Form with 2 Text fields, _Text 1_ and _Text 2_
2. Add a Rule: **IF** ‘Text 1’ _is not equal to_ ‘Value’ _”test”_ **DO** _Show_ “Text 2”
3. Save Rule
4. Save Form
5. Click into Form to Edit

_Result:_ Console errors are thrown and you cannot edit the Form. If you continue to add the Form to a page, the rule does still get applied. However, you cannot click into the Form to do any edits.
[Error message on portlet](http://i.imgur.com/BOna5Ik.png)
[Errors thrown in console](https://gist.github.com/ctampoya/e3d62319d1ae60b90dedc49fa593b61e)

**Note** This also happens when the condition is set to “does not contain”

**Comment by marcellustavares** [comment]
Thanks for catching these issues Clarissa. Id propose to leave the story in
progress but push to master this batch if we're no causing any regressions.

This pull is already big enough.

Thanks

Em 6 de out de 2016 9:15 PM, "Clarissa Tampoya" notifications@github.com
escreveu:

**Comment by ctampoya** [comment]
@marcellustavares I did not find any regressions with the pull. I would like to get the test written first and then I can get this batch pushed to master with the POSHI test.

**Comment by marcellustavares** [comment]
Awesome, thanks Clarissa!

Em 6 de out de 2016 9:42 PM, "Clarissa Tampoya" notifications@github.com
escreveu:

**Comment by ctampoya** [comment]
Pushed to https://github.com/sharonchoi/liferay-portal/pull/910

**Comment by marcellustavares** [comment]
cc @thiago-rocha

**Pull request closed without merging**
