### PR TITLE
LPS-70446 SF

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by ctampoya** [comment]
@thiago-rocha There's a SF error on this pull `Missing language key 'autofill': ./modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-form-web/src/main/resources/META-INF/resources/admin/js/form_builder_render_rule.js`

**Comment by ctampoya** [comment]
@thiago-rocha  Could you also take a look at the failing unit test? `GetDataProviderParametersSettingsMVCResourceCommandTest.testCreateParametersJSONObject`

**Comment by thiago-rocha** [comment]
@rafaprax Could you also take a look at the failing unit test? `GetDataProviderParametersSettingsMVCResourceCommandTest.testCreateParametersJSONObject`

=P

**Comment by rafaprax** [comment]
@thiago-rocha resent to you https://github.com/thiago-rocha/liferay-portal/pull/64

**Pull request closed without merging**
