### PR TITLE
LPS-70097 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by ctampoya** [comment]
ci:reopen

**Comment by ctampoya** [comment]
ci:retest

**Comment by rafaprax** [comment]
Hey @ctampoya,

The failures in `Forms#ConfigureDataProviderWithSelectField` and `Forms#ConfigureAutocompleteWithTextField` are real. Those tests are broken now because I've removed the displayed and stored attributes from data provider add page. So, because of that, we have two changes in the way how to use data providers in forms.

- Now we are using the output parameter section instead of the removed fields(displayed and stored attributes). You can use as reference the changes in https://github.com/ctampoya/liferay-portal/pull/66/commits/27c894780409d597c910a39e50d5e539d8acfc59?diff=split#diff-f80584a72c055afac5030b2473e6798f.

- When the form builder wants to use data providers with select and text fields, he/she should select the output parameter that will be used to fill the options(in case of select fields) or the suggestion list(in case of text with autocomplete).

Let me know if you have any doubts. Thx :)

**Comment by ctampoya** [comment]
Pushed to
https://github.com/vicnate5/liferay-portal/pull/726

**Pull request closed without merging**
