### PR TITLE
LPS-70895 SF

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
hey @ctampoya , could you take a look on that? :) It's the DDL part of LPS-70895

**Comment by ctampoya** [comment]
ci:stop

**Comment by ctampoya** [comment]
ci:retest

**Comment by ctampoya** [comment]
@pedroqueiroz94  Is that unit test failure related to the pull?

**Comment by pedroqueiroz** [comment]
@ctampoya yeah, it is. My bad, I'm going to take a look on it.

**Comment by ctampoya** [comment]
@pedroqueiroz94 Sounds good. I'll close this pull.

**Pull request closed without merging**
