### PR TITLE
LPS-69107 regen system.packages.extra.mf

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by ctampoya** [comment]
ci:reopen

**Comment by ctampoya** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@linolaoj  There seems to be an issue with the version numbers that keeps causing failures on almost all the tests. Maybe it needs a rebase and a regen again?

**Comment by linolaoj** [comment]
Thank you @vicnate5,
resent https://github.com/ctampoya/liferay-portal/pull/49

**Pull request closed without merging**
