### PR TITLE
LPS-70564 SF

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by ctampoya** [comment]
ci:retest

**Comment by ctampoya** [comment]
@diogo-lins A few Forms tests failed with this pull. I have listed the tests below.  I am looking into them right now.
[FormRules#ConfigureShowRuleUsingAndCondition](https://testray.liferay.com/home/-/testray/case_results/67050029)
[FormRules#ConfigureAutofillRule](https://testray.liferay.com/home/-/testray/case_results/67050793)
[FormsJumpToPage#ViewPagesAfterJump](https://testray.liferay.com/home/-/testray/case_results/67050571)
[FormRules#EditRule](https://testray.liferay.com/home/-/testray/case_results/67050856)
[FormRules#ConfigureRequireRule](https://testray.liferay.com/home/-/testray/case_results/67050855)
[WorkflowForms#ViewEntryWithConditionalVisibilityFromSelectAndRadio](https://testray.liferay.com/home/-/testray/case_results/67050114)

**Comment by ctampoya** [comment]
@diogo-lins  Could you take another look at this please? There is an error when trying to save a Form that contains a rule. 

###### Steps to reproduce:
1. Add a Form with a Text and Date field
2. Create a rule: If Text field is equal to test -> Require Date field
3. Save rule
4. View rule summary 
5. Save Form

_Expected:_ You should see the created rule in the rule summary and the Form should successfully save.
_Actual:_ The Rule does not get saved and when you try to save the Form, the portlet becomes unavailable and an error is thrown in the console.
```
20:57:29,110 ERROR [http-nio-8080-exec-10][render_portlet_jsp:131] null
java.lang.NullPointerException
        at com.liferay.dynamic.data.lists.form.web.internal.converter.DDLFormRuleDeserializer.deserializeDDLFormRuleConditions(DDLFormRuleDeserializer.java:119)
        at com.liferay.dynamic.data.lists.form.web.internal.converter.DDLFormRuleDeserializer.deserializeDDLFormRule(DDLFormRuleDeserializer.java:68)
        at com.liferay.dynamic.data.lists.form.web.internal.converter.DDLFormRuleDeserializer.deserialize(DDLFormRuleDeserializer.java:50)
        at com.liferay.dynamic.data.lists.form.web.internal.portlet.action.SaveRecordSetMVCCommandHelper.getDDMFormRules(SaveRecordSetMVCCommandHelper.java:224)
        at com.liferay.dynamic.data.lists.form.web.internal.portlet.action.SaveRecordSetMVCCommandHelper.getDDMForm(SaveRecordSetMVCCommandHelper.java:188)
        at com.liferay.dynamic.data.lists.form.web.internal.portlet.action.SaveRecordSetMVCCommandHelper.updateDDMStructure(SaveRecordSetMVCCommandHelper.java:299)
        at com.liferay.dynamic.data.lists.form.web.internal.portlet.action.SaveRecordSetMVCCommandHelper.updateRecordSet(SaveRecordSetMVCCommandHelper.java:340)
        at com.liferay.dynamic.data.lists.form.web.internal.portlet.action.SaveRecordSetMVCCommandHelper.saveRecordSet(SaveRecordSetMVCCommandHelper.java:84)
        at com.liferay.dynamic.data.lists.form.web.internal.portlet.action.SaveRecordSetMVCActionCommand.doTransactionalCommand(SaveRecordSetMVCActionCommand.java:65)
        at com.liferay.portal.kernel.portlet.bridges.mvc.BaseTransactionalMVCActionCommand$1.call(BaseTransactionalMVCActionCommand.java:45)
        at com.liferay.portal.kernel.portlet.bridges.mvc.BaseTransactionalMVCActionCommand$1.call(BaseTransactionalMVCActionCommand.java:41)
        at com.liferay.portal.spring.transaction.TransactionInvokerImpl$CallableMethodInvocation.proceed(TransactionInvokerImpl.java:101)
        at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:54)
        at com.liferay.portal.spring.transaction.TransactionInvokerImpl.invoke(TransactionInvokerImpl.java:47)
        at com.liferay.portal.kernel.transaction.TransactionInvokerUtil.invoke(TransactionInvokerUtil.java:28)
        at com.liferay.portal.kernel.portlet.bridges.mvc.BaseTransactionalMVCActionCommand.processAction(BaseTransactionalMVCActionCommand.java:52)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:365)
        at com.liferay.portal.kernel.portlet.LiferayPortlet.processAction(LiferayPortlet.java:93)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.processAction(MVCPortlet.java:258)
        at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:71)
```

**Comment by diogo-lins** [comment]
Okay @ctampoya I will take a look right now!

**Comment by diogo-lins** [comment]
Fix here (https://github.com/ctampoya/liferay-portal/pull/104)

**Pull request closed without merging**
