### PR TITLE
LPS-71772 Fix remaining link

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by ctampoya** [comment]
@marcellustavares Is that failure due to changes made in this pull?

**Comment by marcellustavares** [comment]
@ctampoya, it's not related.

**Comment by marcellustavares** [comment]
ci:retest

**Comment by ctampoya** [comment]
ci:reopen

**Comment by ctampoya** [comment]
ci:retest

**Comment by ctampoya** [comment]
[Testray](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=70232552)

**Comment by ctampoya** [comment]
Pushed to https://github.com/vicnate5/liferay-portal/pull/802

**Pull request closed without merging**
